# Site settings
title: Pay Special Mind
header-img: img/home-bg.png
email: lucia.adam@gmail.com
copyright_name: aml7733
description: > # this means to ignore newlines until "baseurl:"
  A journey of code and discovery
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  aml7733
learn_profile: aml7733
email_username: lucia.adam@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
